language: node_js
node_js:
  - "10"
addons:
  sonarcloud:
    organization: "brunopacheco1-github"
    token:
      secure: $SONAR_KEY
script:
  - npm test
  - sonar-scanner
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY